apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: prod
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  hostPath:
   path: /mnt/data-prod
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: prod
spec:
 storageClassName: slow
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 2Gi
