apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: dev
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
data:
  primary.cnf: |
    [mysqld]
    log-bin
  replica.cnf: |
    [mysqld]
    super-read-only
---
