apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookmark-app
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: bookmark-chart/
    repoURL: 'https://github.com/AMM48/ClusterDeploy'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
