apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-bookmark-app
    tier: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      tier: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        tier: {{ .Release.Name }}-api
    spec:
      containers:
      - name: bookmark-app-api
        image: {{ .Values.image.appImage }}:{{ .Values.image.apiTag }}
        imagePullPolicy: Always
        env:
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: host
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_name
