apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-bookmark-app
    tier: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      tier: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        tier: {{ .Release.Name }}-api
    spec:
      securityContext:
        runAsUser: {{ .Values.podSecurityContext.api.user }}
        runAsGroup: {{ .Values.podSecurityContext.api.group }}
        fsGroup: {{ .Values.podSecurityContext.api.fsGroup }}
        runAsNonRoot: {{ .Values.podSecurityContext.api.runAsNonRoot }}
      containers:
      - name: bookmark-app-api
        image: {{ .Values.image.appImage }}:{{ .Values.image.apiTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          runAsUser: {{ .Values.securityContext.api.user }}
          runAsGroup: {{ .Values.securityContext.api.group }}
          runAsNonRoot: {{ .Values.securityContext.api.runAsNonRoot }}
          allowPrivilegeEscalation: {{ .Values.securityContext.api.allowPrivilegeEscalation }}
          capabilities:
            drop:
              {{- range .Values.securityContext.api.capabilities.drop }}
              - {{ . }}
              {{- end }}
        env:
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: host
        - name: READ_HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: read_host
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: admin_username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: admin_password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_name
---
