apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-db-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-db
  policyTypes:
  {{- range .Values.networkPolicy.db.policyType }}
  - {{ . }}
  {{- end }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-db
    - podSelector:
        matchLabels:
          tier: {{ .Release.Name }}-api
    ports:
    {{- range .Values.networkPolicy.db.ports }}
    - protocol: {{ .protocol }}
      port: {{ .port }}
    {{- end }}
---
