apiVersion: v1
kind: Service
metadata:
  name: dbsvc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-dbsvc
spec:
  clusterIP: None
  ports:
  - port: 3306
  selector:
    app: {{ .Release.Name }}-db
---
apiVersion: v1
kind: Service
metadata:
  name: dbsvc-read
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-dbsvc-read
    readonly: "true"
spec:
  ports:
  - port: 3306
  selector:
    app: {{ .Release.Name }}-db
---
apiVersion: v1
kind: Service
metadata:
  name: apisvc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    tier: {{ .Release.Name }}-api
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: clientsvc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    tier: {{ .Release.Name }}-frontend
  ports:
    - port: 80
      targetPort: 3000
---
