apiVersion: v1
kind: Service
metadata:
  name: dbsvc
  labels:
    app: {{ .Release.Name }}-dbsvc
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.services.dbsvc.port }}
      targetPort: {{ .Values.services.dbsvc.targetPort }}
  selector:
    app: {{ .Release.Name }}-db
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-apisvc
spec:
  type: NodePort
  selector:
    tier: {{ .Release.Name }}-api
  ports:
    - port: {{ .Values.services.apisvc.port }}
      targetPort: {{ .Values.services.apisvc.targetPort }}
      nodePort: {{ .Values.services.apisvc.nodePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-clientsvc
spec:
  selector:
    tier: {{ .Release.Name }}-frontend
  ports:
    - port: {{ .Values.services.clientsvc.port }}
      targetPort: {{ .Values.services.clientsvc.targetPort }}
