apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-db-pv
spec:
  capacity:
    storage: {{ .Values.pv.capacity.storage }}
  volumeMode: {{ .Values.pv.volumeMode }}
  accessModes:
  - {{ .Values.pv.accessModes | quote }}
  persistentVolumeReclaimPolicy: {{ .Values.pv.persistentVolumeReclaimPolicy }}
  storageClassName: {{ .Values.pv.storageClassName }}
  hostPath:
    path: {{ .Values.pv.hostPath.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-pvc
spec:
 storageClassName: {{ .Values.pvc.storageClassName }}
 accessModes:
 - {{ .Values.pvc.accessModes | quote }}
 resources:
  requests:
   storage: {{ .Values.pvc.storage }}
